version: "3.5"

services:
  scraper-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - scraper
  nginx:
    image: nginx
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./config/nginx/:/etc/nginx/conf.d/
    ports:
      - 8000:80
    networks:
      - scraper
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel-scraper
      MYSQL_ROOT_PASSWORD: 12345
    working_dir: /var/backups
    ports:
      - 3309:3306
    networks:
      - scraper
networks:
  scraper:
    driver: bridge